##
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd
server:
  port: 8888

resource:
  imageServer: http://images.hgz1.com
  emailServer: http://email.hgz1.com

